development:
  adapter: mysql2
  encoding: utf8
  database: weirdtest_development
  pool: 5
  username: root

test:
  adapter: mysql2
  encoding: utf8
  database: weirdtest_test
  pool: 5
  username: root

production:
  adapter: mysql2
  encoding: utf8
  database: weirdtest_production
  pool: 5
  username: root
